# Workflow to Automatically Update Data Sources in the Repository / Development Branch
name: API - Automated Data Updates (Development Branch)

# Controls when the action will run. 
on:
  
  # Time-based workflow trigger (at 00:10, 08:10, 16:10)
  schedule:
    - cron: '*/5 * * * *'  
    
# The job executed by the workflow
jobs:
  
  # This workflow contains a single job called "update_data_sources"
  api_update_data_sources:
    
    # This job runs on Linux using Python 3.7 version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # The sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: development

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
             
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Configure Git Credentials
        run: |
          echo ${{ github.workspace }}
          git config --local user.email "action@agithub.com"
          git config --local user.name "GitHub Action"
        
      - name: Update Data
        run: |
          cd ${{ github.workspace }}
          python update_data.py
          
      - name: Commit files
        run: |
          git add -A
          git commit -m "Automated Data Update using Workflows"
      
      - name: Push changes to development branch                               
        uses: ad-m/github-push-action@master
        with:
          branch: development                                 
          github_token: ${{ secrets.GITHUB_TOKEN }}
